In [34]:
import pandas as pd

In [ ]:
Using the package / module pandas to make tables.

In [11]:
a = [3, 4, 0, 8]
b = [8, 10, 2, 8]
c = [1, 6, 0, 7]

In [15]:
arla = pd.DataFrame({'person 1': a, 'person 2': b, 'person 3': c})

In [16]:
type(arla)

pandas.DataFrame

In [17]:
arla

   person 1  person 2  person 3
0         3         8         1
1         4        10         6
2         0         2         0
3         8         8         7

In [19]:
arla['person 1']

0    3
1    4
2    0
3    8
Name: person 1, dtype: int64

In [23]:
d = arla['person 1']

In [24]:
type(d)

pandas.Series

In [25]:
e = list(d)

In [26]:
e

[3, 4, 0, 8]

In [27]:
arla["row_mean"] = arla.mean(axis=1)

In [28]:
arla

   person 1  person 2  person 3  row_mean
0         3         8         1  4.000000
1         4        10         6  6.666667
2         0         2         0  0.666667
3         8         8         7  7.666667

In [36]:
df = pd.read_csv('/work/E2026/Repository1/Stroop-raw-over-the-years.csv')

In [37]:
df

     Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int  Year
0             4.16        6.76          4.45         4.65  2015
1             4.35        7.73          4.78         4.46  2015
2             3.60        7.00          4.00         3.50  2015
3             3.90        9.03          4.60         6.30  2015
4             4.22        9.98          6.83         6.24  2015
..             ...         ...           ...          ...   ...
200           4.77       10.00          5.66         6.24  2025
201           4.61       12.80          6.87         9.55  2025
202           4.79       10.72          5.64         7.25  2025
203           4.41        8.87          6.70         6.70  2025
204           5.50        9.80          6.20        21.70  2025

[205 rows x 5 columns]

In [47]:
df

,Reading_NoInt,Naming_Int,Naming_NoInt,Reading_Int,Year,row_mean,columns_mean
0,4.16,6.76,4.45,4.65,2015,407.004,407.004
1,4.35,7.73,4.78,4.46,2015,407.264,407.264
2,3.60,7.00,4.00,3.50,2015,406.620,406.620
3,3.90,9.03,4.60,6.30,2015,407.766,407.766
4,4.22,9.98,6.83,6.24,2015,408.454,408.454
...,...,...,...,...,...,...,...
200,4.77,10.00,5.66,6.24,2025,410.334,410.334
201,4.61,12.80,6.87,9.55,2025,411.766,411.766
202,4.79,10.72,5.64,7.25,2025,410.680,410.680
203,4.41,8.87,6.70,6.70,2025,410.336,410.336
204,5.50,9.80,6.20,21.70,2025,413.640,413.640

In [48]:
df = df[0:4]

In [49]:
df

,Reading_NoInt,Naming_Int,Naming_NoInt,Reading_Int,Year,row_mean,columns_mean
0,4.16,6.76,4.45,4.65,2015,407.004,407.004
1,4.35,7.73,4.78,4.46,2015,407.264,407.264
2,3.60,7.00,4.00,3.50,2015,406.620,406.620
3,3.90,9.03,4.60,6.30,2015,407.766,407.766

In [50]:
df = pd.read_csv('/work/E2026/Repository1/Stroop-raw-over-the-years.csv')

In [51]:
df

     Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int  Year
0             4.16        6.76          4.45         4.65  2015
1             4.35        7.73          4.78         4.46  2015
2             3.60        7.00          4.00         3.50  2015
3             3.90        9.03          4.60         6.30  2015
4             4.22        9.98          6.83         6.24  2015
..             ...         ...           ...          ...   ...
200           4.77       10.00          5.66         6.24  2025
201           4.61       12.80          6.87         9.55  2025
202           4.79       10.72          5.64         7.25  2025
203           4.41        8.87          6.70         6.70  2025
204           5.50        9.80          6.20        21.70  2025

[205 rows x 5 columns]

In [52]:
df = df.drop(['Year'],axis=1)

In [53]:
df

     Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int
0             4.16        6.76          4.45         4.65
1             4.35        7.73          4.78         4.46
2             3.60        7.00          4.00         3.50
3             3.90        9.03          4.60         6.30
4             4.22        9.98          6.83         6.24
..             ...         ...           ...          ...
200           4.77       10.00          5.66         6.24
201           4.61       12.80          6.87         9.55
202           4.79       10.72          5.64         7.25
203           4.41        8.87          6.70         6.70
204           5.50        9.80          6.20        21.70

[205 rows x 4 columns]

In [64]:
Reading_NoInt = df['Naming_Int'].mean()

In [65]:
Reading_NoInt

np.float64(9.584780487804878)

In [66]:
df.loc[205]=df.mean(axis=0)

In [67]:
df

     Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int
0         4.160000     6.76000      4.450000     4.650000
1         4.350000     7.73000      4.780000     4.460000
2         3.600000     7.00000      4.000000     3.500000
3         3.900000     9.03000      4.600000     6.300000
4         4.220000     9.98000      6.830000     6.240000
..             ...         ...           ...          ...
201       4.610000    12.80000      6.870000     9.550000
202       4.790000    10.72000      5.640000     7.250000
203       4.410000     8.87000      6.700000     6.700000
204       5.500000     9.80000      6.200000    21.700000
205       4.472244     9.58478      5.973805     5.787366

[206 rows x 4 columns]

In [69]:
df.loc[206]= 'mean'

In [70]:
df

    Reading_NoInt Naming_Int Naming_NoInt Reading_Int
0            4.16       6.76         4.45        4.65
1            4.35       7.73         4.78        4.46
2             3.6        7.0          4.0         3.5
3             3.9       9.03          4.6         6.3
4            4.22       9.98         6.83        6.24
..            ...        ...          ...         ...
202          4.79      10.72         5.64        7.25
203          4.41       8.87          6.7         6.7
204           5.5        9.8          6.2        21.7
205      4.472244    9.58478     5.973805    5.787366
206          mean       mean         mean        mean

[207 rows x 4 columns]

In [78]:
df.drop([0, 206])

    Reading_NoInt Naming_Int Naming_NoInt Reading_Int
1            4.35       7.73         4.78        4.46
2             3.6        7.0          4.0         3.5
3             3.9       9.03          4.6         6.3
4            4.22       9.98         6.83        6.24
5            4.31       6.51         5.78        4.08
..            ...        ...          ...         ...
201          4.61       12.8         6.87        9.55
202          4.79      10.72         5.64        7.25
203          4.41       8.87          6.7         6.7
204           5.5        9.8          6.2        21.7
205      4.472244    9.58478     5.973805    5.787366

[205 rows x 4 columns]